### ISSUE TITLE
Great code, but doesnt work with last version of node-signpdf

### ISSUE THREAD

**Issue by nilopaim** [MohammedEssehemy/node-sign-validate-pdf#1]
Using node-signpdf version 1.2.3 your code gives me 

`node:1316) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fonts' of undefined
    at PDFDocument.endAcroForm (D:\Micromed\sign\node_modules\pdfkit\js\pdfkit.js:4900:39)
    at PDFDocument.end (D:\Micromed\sign\node_modules\pdfkit\js\pdfkit.js:5506:10)
    at D:\Micromed\sign\sign.js:159:9
    at new Promise (<anonymous>)
    at creatPDF (D:\Micromed\sign\sign.js:64:3)
    at signFunc (D:\Micromed\sign\sign.js:276:27)
    at main (D:\Micromed\sign\sign.js:355:9)
    at Object.<anonymous> (D:\Micromed\sign\sign.js:359:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
(node:1316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Any hints?

**Comment by MohammedEssehemy** [comment]
@nilopaim you might check the [verify-pdf](https://github.com/ninja-labs-tech/verify-pdf) project

**Comment by nilopaim** [comment]
@MohammedEssehemy thanks for the hint. I'll check later.
